version: "3.8"

services:
  snake:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Map host port 5000 to container port 80
    container_name: snake-game
    restart: unless-stopped
